# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Whalegroup
email: co.whalegroup@gmail.com
description: Database에 관심이 많은 잡덕
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whalegroup.github.io/" # the base hostname & protocol for your site
twitter_username: whalegroup
github_username:  whalegroup
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
